first_item = '//div[@class="listItem"]/div[contains(@class, "ls-elem")][1]'
price = f'{first_item}//div[@class="ls-data-price"]/span[1]'
mileage = f'{first_item}//div[@class="ls-data-additional"]/div[1]'
href = f'{first_item}//div[@class="ls-titles"]/a'
params = '//ul[@class="columns"]/li'
description = '//div[contains(@data-type, "description")]'
description_title = '//div[contains(@data-target, "description")]/h3/label'
title = f'{first_item}//h2'

pages = '//ul[@class="sc-pagination"]/li[not(contains(@class, "e"))]/a[not(@class="active")]'

vehicle_type_id_filter = '//select[@id="vehicleTypeId"]/option[@selected="selected"]'
substructure_id_filter = '//select[@id="substructureId"]/option[@selected="selected"]'
make_id_filter = '//select[@id="makeId"]/option[@selected="selected"]'
country_id_filter = '//select[@id="countryId"]/option[@selected="selected"]'
price_type_filter = '//input[@name="priceType"][@checked]'
model_filter = '//input[@id="model"]'
price_from_filter = '//input[@id="priceFrom"]'
price_to_filter = '//input[@id="priceTo"]'
request_verification_token_filter = '//input[@name="__RequestVerificationToken"]'
